<?xml version="1.0" encoding="utf-8"?><Database Name="trainmanage" Class="trainmanageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KHDT-HIEU\;Initial Catalog=trainmanage;Persist Security Info=True;User ID=sa" SettingsObjectName="TrainingManagement.Properties.Settings" SettingsPropertyName="trainmanageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblChuongTrinhDaoTao" Member="tblChuongTrinhDaoTaos">
    <Type Name="tblChuongTrinhDaoTao">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblChuongTrinhDaoTao_tblMonHoc" Member="tblMonHocs" ThisKey="id" OtherKey="idchuongtrinh" Type="tblMonHoc" />
    </Type>
  </Table>
  <Table Name="dbo.tblTrangThai" Member="tblTrangThais">
    <Type Name="tblTrangThai">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="matrangthai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblTrangThai_tblSinhVien" Member="tblSinhViens" ThisKey="id" OtherKey="idtrangthai" Type="tblSinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.tblHocKy" Member="tblHocKies">
    <Type Name="tblHocKy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mahocky" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenhocky" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblHocKy_tblMonHoc" Member="tblMonHocs" ThisKey="id" OtherKey="idhocky" Type="tblMonHoc" />
    </Type>
  </Table>
  <Table Name="dbo.tblKetQua" Member="tblKetQuas">
    <Type Name="tblKetQua">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idsinhvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idmonhoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hanhkiem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblMonHoc_tblKetQua" Member="tblMonHoc" ThisKey="idmonhoc" OtherKey="id" Type="tblMonHoc" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tblSinhVien_tblKetQua" Member="tblSinhVien" ThisKey="idsinhvien" OtherKey="id" Type="tblSinhVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblKhoa" Member="tblKhoas">
    <Type Name="tblKhoa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="makhoa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sodienthoai" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Association Name="tblKhoa_tblLop" Member="tblLops" ThisKey="id" OtherKey="idkhoa" Type="tblLop" />
    </Type>
  </Table>
  <Table Name="dbo.tblLop" Member="tblLops">
    <Type Name="tblLop">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idkhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idnienkhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="malop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="siso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblLop_tblSinhVien" Member="tblSinhViens" ThisKey="id" OtherKey="idlop" Type="tblSinhVien" />
      <Association Name="tblKhoa_tblLop" Member="tblKhoa" ThisKey="idkhoa" OtherKey="id" Type="tblKhoa" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tblNienKhoa_tblLop" Member="tblNienKhoa" ThisKey="idnienkhoa" OtherKey="id" Type="tblNienKhoa" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblMonHoc" Member="tblMonHocs">
    <Type Name="tblMonHoc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idchuongtrinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idhocky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idtinchi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mamonhoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblMonHoc_tblKetQua" Member="tblKetQuas" ThisKey="id" OtherKey="idmonhoc" Type="tblKetQua" />
      <Association Name="tblChuongTrinhDaoTao_tblMonHoc" Member="tblChuongTrinhDaoTao" ThisKey="idchuongtrinh" OtherKey="id" Type="tblChuongTrinhDaoTao" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="tblHocKy_tblMonHoc" Member="tblHocKy" ThisKey="idhocky" OtherKey="id" Type="tblHocKy" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="tblTinChi_tblMonHoc" Member="tblTinChi" ThisKey="idtinchi" OtherKey="id" Type="tblTinChi" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblNienKhoa" Member="tblNienKhoas">
    <Type Name="tblNienKhoa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="manienkhoa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nambatdau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="namketthuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="tblNienKhoa_tblLop" Member="tblLops" ThisKey="id" OtherKey="idnienkhoa" Type="tblLop" />
    </Type>
  </Table>
  <Table Name="dbo.tblSinhVien" Member="tblSinhViens">
    <Type Name="tblSinhVien">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idlop" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idtrangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="noisinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblSinhVien_tblKetQua" Member="tblKetQuas" ThisKey="id" OtherKey="idsinhvien" Type="tblKetQua" />
      <Association Name="tblLop_tblSinhVien" Member="tblLop" ThisKey="idlop" OtherKey="id" Type="tblLop" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tblTrangThai_tblSinhVien" Member="tblTrangThai" ThisKey="idtrangthai" OtherKey="id" Type="tblTrangThai" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTaiKhoan" Member="tblTaiKhoans">
    <Type Name="tblTaiKhoan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblTaiKhoan_tblThongTin" Member="tblThongTins" ThisKey="id" OtherKey="idtaiKhoan" Type="tblThongTin" />
    </Type>
  </Table>
  <Table Name="dbo.tblThongTin" Member="tblThongTins">
    <Type Name="tblThongTin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idtaiKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="chucvu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblTaiKhoan_tblThongTin" Member="tblTaiKhoan" ThisKey="idtaiKhoan" OtherKey="id" Type="tblTaiKhoan" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTinChi" Member="tblTinChis">
    <Type Name="tblTinChi">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="matinchi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sotinchi" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="tblTinChi_tblMonHoc" Member="tblMonHocs" ThisKey="id" OtherKey="idtinchi" Type="tblMonHoc" />
    </Type>
  </Table>
  <Function Name="dbo.sp_checkAccountGroup" Method="sp_checkAccountGroup">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="passuser" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_changePassword" Method="st_changePassword">
    <Parameter Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="passcu" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="passmoi" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getGiaoVienID" Method="sp_getGiaoVienID">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getQuanLyVienID" Method="sp_getQuanLyVienID">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getSinhVienID" Method="sp_getSinhVienID">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_login" Method="sp_login">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_LoginSV" Method="sp_LoginSV">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_LoginSVResult">
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_Delete" Method="sp_tblChuongTrinhDaoTao_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_FindDanhSachMonHocID" Method="sp_tblChuongTrinhDaoTao_FindDanhSachMonHocID">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblChuongTrinhDaoTao_FindDanhSachMonHocIDResult">
      <Column Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_FindDanhSachMonHocName" Method="sp_tblChuongTrinhDaoTao_FindDanhSachMonHocName">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblChuongTrinhDaoTao_FindDanhSachMonHocNameResult">
      <Column Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_Insert" Method="sp_tblChuongTrinhDaoTao_Insert">
    <Parameter Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_SelectAll" Method="sp_tblChuongTrinhDaoTao_SelectAll">
    <ElementType Name="sp_tblChuongTrinhDaoTao_SelectAllResult">
      <Column Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_SelectID" Method="sp_tblChuongTrinhDaoTao_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblChuongTrinhDaoTao_SelectIDResult">
      <Column Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblChuongTrinhDaoTao_Update" Method="sp_tblChuongTrinhDaoTao_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="machuongtrinh" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblHocKy_Delete" Method="sp_tblHocKy_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblHocKy_Insert" Method="sp_tblHocKy_Insert">
    <Parameter Name="mahocky" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenhocky" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblHocKy_SelectAll" Method="sp_tblHocKy_SelectAll">
    <ElementType Name="sp_tblHocKy_SelectAllResult">
      <Column Name="mahocky" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenhocky" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblHocKy_SelectID" Method="sp_tblHocKy_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblHocKy_SelectIDResult">
      <Column Name="mahocky" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenhocky" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblHocKy_Update" Method="sp_tblHocKy_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="mahocky" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenhocky" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKetQua_BangtotNghiepSinhVien" Method="sp_tblKetQua_BangtotNghiepSinhVien">
    <ElementType Name="sp_tblKetQua_BangtotNghiepSinhVienResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenhocky" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hanhkiem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKetQua_Delete" Method="sp_tblKetQua_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKetQua_Insert" Method="sp_tblKetQua_Insert">
    <Parameter Name="idsinhvien" Type="System.Int32" DbType="Int" />
    <Parameter Name="idmonhoc" Type="System.Int32" DbType="Int" />
    <Parameter Name="diemtrungbinh" Type="System.Double" DbType="Float" />
    <Parameter Name="diemthilan1" Type="System.Double" DbType="Float" />
    <Parameter Name="diemthilan2" Type="System.Double" DbType="Float" />
    <Parameter Name="diemtongket" Type="System.Double" DbType="Float" />
    <Parameter Name="hanhkiem" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKetQua_MonHocSinhVien" Method="sp_tblKetQua_MonHocSinhVien">
    <ElementType Name="sp_tblKetQua_MonHocSinhVienResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKetQua_SelectAll" Method="sp_tblKetQua_SelectAll">
    <ElementType Name="sp_tblKetQua_SelectAllResult">
      <Column Name="idsinhvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idmonhoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hanhkiem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKetQua_SelectID" Method="sp_tblKetQua_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblKetQua_SelectIDResult">
      <Column Name="idsinhvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idmonhoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hanhkiem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKetQua_Update" Method="sp_tblKetQua_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idsinhvien" Type="System.Int32" DbType="Int" />
    <Parameter Name="idmonhoc" Type="System.Int32" DbType="Int" />
    <Parameter Name="diemtrungbinh" Type="System.Double" DbType="Float" />
    <Parameter Name="diemthilan1" Type="System.Double" DbType="Float" />
    <Parameter Name="diemthilan2" Type="System.Double" DbType="Float" />
    <Parameter Name="diemtongket" Type="System.Double" DbType="Float" />
    <Parameter Name="hanhkiem" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKetQua_View" Method="sp_tblKetQua_View">
    <ElementType Name="sp_tblKetQua_ViewResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenhocky" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKhoa_Delete" Method="sp_tblKhoa_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKhoa_Insert" Method="sp_tblKhoa_Insert">
    <Parameter Name="makhoa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenkhoa" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sodienthoai" Type="System.String" DbType="VarChar(11)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblKhoa_SelectAll" Method="sp_tblKhoa_SelectAll">
    <ElementType Name="sp_tblKhoa_SelectAllResult">
      <Column Name="makhoa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sodienthoai" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblKhoa_Update" Method="sp_tblKhoa_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="makhoa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenkhoa" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sodienthoai" Type="System.String" DbType="VarChar(11)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblLop_Delete" Method="sp_tblLop_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblLop_Insert" Method="sp_tblLop_Insert">
    <Parameter Name="idkhoa" Type="System.Int32" DbType="Int" />
    <Parameter Name="idnienkhoa" Type="System.Int32" DbType="Int" />
    <Parameter Name="malop" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenlop" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="siso" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblLop_SelectAll" Method="sp_tblLop_SelectAll">
    <ElementType Name="sp_tblLop_SelectAllResult">
      <Column Name="idkhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idnienkhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="malop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="siso" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblLop_SelectID" Method="sp_tblLop_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblLop_SelectIDResult">
      <Column Name="idkhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idnienkhoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="malop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="siso" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblLop_Update" Method="sp_tblLop_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idkhoa" Type="System.Int32" DbType="Int" />
    <Parameter Name="idnienkhoa" Type="System.Int32" DbType="Int" />
    <Parameter Name="malop" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenlop" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="siso" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblLop_View" Method="sp_tblLop_View">
    <ElementType Name="sp_tblLop_ViewResult">
      <Column Name="malop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="siso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblLop_ViewYear" Method="sp_tblLop_ViewYear">
    <ElementType Name="sp_tblLop_ViewYearResult">
      <Column Name="malop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="siso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nambatdau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="namketthuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMonHoc_Delete" Method="sp_tblMonHoc_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblMonHoc_FindDanhSachSinhVien" Method="sp_tblMonHoc_FindDanhSachSinhVien">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblMonHoc_FindDanhSachSinhVienResult">
      <Column Name="mamonhoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMonHoc_Insert" Method="sp_tblMonHoc_Insert">
    <Parameter Name="idchuongtrinh" Type="System.Int32" DbType="Int" />
    <Parameter Name="idhocky" Type="System.Int32" DbType="Int" />
    <Parameter Name="idtinchi" Type="System.Int32" DbType="Int" />
    <Parameter Name="mamonhoc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblMonHoc_SelectAll" Method="sp_tblMonHoc_SelectAll">
    <ElementType Name="sp_tblMonHoc_SelectAllResult">
      <Column Name="idchuongtrinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idhocky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idtinchi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mamonhoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMonHoc_SelectID" Method="sp_tblMonHoc_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblMonHoc_SelectIDResult">
      <Column Name="idchuongtrinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idhocky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idtinchi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mamonhoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMonHoc_Update" Method="sp_tblMonHoc_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idchuongtrinh" Type="System.Int32" DbType="Int" />
    <Parameter Name="idhocky" Type="System.Int32" DbType="Int" />
    <Parameter Name="idtinchi" Type="System.Int32" DbType="Int" />
    <Parameter Name="mamonhoc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblMonHoc_View" Method="sp_tblMonHoc_View">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblMonHoc_ViewResult">
      <Column Name="[Mã môn học]" Member="Mã_môn_học" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Tên môn học]" Member="Tên_môn_học" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Tên chương trình]" Member="Tên_chương_trình" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Tên học kỳ]" Member="Tên_học_kỳ" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Số tín chỉ]" Member="Số_tín_chỉ" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblNienKhoa_Delete" Method="sp_tblNienKhoa_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblNienKhoa_Insert" Method="sp_tblNienKhoa_Insert">
    <Parameter Name="manienkhoa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="nambatdau" Type="System.DateTime" DbType="Date" />
    <Parameter Name="namketthuc" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblNienKhoa_SelectAll" Method="sp_tblNienKhoa_SelectAll">
    <ElementType Name="sp_tblNienKhoa_SelectAllResult">
      <Column Name="manienkhoa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nambatdau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="namketthuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblNienKhoa_SelectID" Method="sp_tblNienKhoa_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblNienKhoa_SelectIDResult">
      <Column Name="manienkhoa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nambatdau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="namketthuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblNienKhoa_Update" Method="sp_tblNienKhoa_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="manienkhoa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tennienkhoa" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="nambatdau" Type="System.DateTime" DbType="Date" />
    <Parameter Name="namketthuc" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblSinhVien_Delete" Method="sp_tblSinhVien_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblSinhVien_FindID" Method="sp_tblSinhVien_FindID">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblSinhVien_FindIDResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="noisinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSinhVien_FindKetQuaMonHocSinhVienID" Method="sp_tblSinhVien_FindKetQuaMonHocSinhVienID">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblSinhVien_FindKetQuaMonHocSinhVienIDResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSinhVien_FindKetQuaMonHocSinhVienName" Method="sp_tblSinhVien_FindKetQuaMonHocSinhVienName">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblSinhVien_FindKetQuaMonHocSinhVienNameResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenchuongtrinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemthilan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemthilan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtongket" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diemtrungbinh" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSinhVien_FindName" Method="sp_tblSinhVien_FindName">
    <Parameter Name="keyword" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_tblSinhVien_FindNameResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="noisinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSinhVien_Insert" Method="sp_tblSinhVien_Insert">
    <Parameter Name="idlop" Type="System.Int32" DbType="Int" />
    <Parameter Name="idtrangthai" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="namsinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gioitinh" Type="System.String" DbType="NVarChar(3)" />
    <Parameter Name="noisinh" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblSinhVien_SelectAll" Method="sp_tblSinhVien_SelectAll">
    <ElementType Name="sp_tblSinhVien_SelectAllResult">
      <Column Name="idlop" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idtrangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="noisinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSinhVien_SelectID" Method="sp_tblSinhVien_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblSinhVien_SelectIDResult">
      <Column Name="idlop" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idtrangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="noisinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSinhVien_Update" Method="sp_tblSinhVien_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idlop" Type="System.Int32" DbType="Int" />
    <Parameter Name="idtrangthai" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="namsinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gioitinh" Type="System.String" DbType="NVarChar(3)" />
    <Parameter Name="noisinh" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblSinhVien_View" Method="sp_tblSinhVien_View">
    <ElementType Name="sp_tblSinhVien_ViewResult">
      <Column Name="masinhvien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tensinhvien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="noisinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_Check" Method="sp_tblTaiKhoan_Check">
    <Parameter Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhau" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="sp_tblTaiKhoan_CheckResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_CheckGroup" Method="sp_tblTaiKhoan_CheckGroup">
    <Parameter Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhau" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_Delete" Method="sp_tblTaiKhoan_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_FindUserID" Method="sp_tblTaiKhoan_FindUserID">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblTaiKhoan_FindUserIDResult">
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="chucvu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_FindUserName" Method="sp_tblTaiKhoan_FindUserName">
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_tblTaiKhoan_FindUserNameResult">
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="chucvu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_Insert" Method="sp_tblTaiKhoan_Insert">
    <Parameter Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhau" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="nhom" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_SelectAll" Method="sp_tblTaiKhoan_SelectAll">
    <ElementType Name="sp_tblTaiKhoan_SelectAllResult">
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_SelectID" Method="sp_tblTaiKhoan_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblTaiKhoan_SelectIDResult">
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTaiKhoan_Update" Method="sp_tblTaiKhoan_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="tentaikhoan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhau" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="nhom" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblThongTin_Delete" Method="sp_tblThongTin_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblThongTin_Insert" Method="sp_tblThongTin_Insert">
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="chucvu" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="namsinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gioitinh" Type="System.String" DbType="NVarChar(3)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblThongTin_SelectAll" Method="sp_tblThongTin_SelectAll">
    <ElementType Name="sp_tblThongTin_SelectAllResult">
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="chucvu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblThongTin_SelectID" Method="sp_tblThongTin_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblThongTin_SelectIDResult">
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="chucvu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="namsinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblThongTin_Update" Method="sp_tblThongTin_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="chucvu" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="namsinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gioitinh" Type="System.String" DbType="NVarChar(3)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblThongTin_View" Method="sp_tblThongTin_View">
    <ElementType Name="sp_tblThongTin_ViewResult">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Tên Tài Khoản]" Member="Tên_Tài_Khoản" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Họ tên]" Member="Họ_tên" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Chức vụ]" Member="Chức_vụ" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Năm sinh]" Member="Năm_sinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Giới tính]" Member="Giới_tính" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="[Địa chỉ]" Member="Địa_chỉ" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTinChi_Delete" Method="sp_tblTinChi_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTinChi_Insert" Method="sp_tblTinChi_Insert">
    <Parameter Name="matinchi" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sotinchi" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTinChi_SelectAll" Method="sp_tblTinChi_SelectAll">
    <ElementType Name="sp_tblTinChi_SelectAllResult">
      <Column Name="matinchi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sotinchi" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTinChi_SelectID" Method="sp_tblTinChi_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblTinChi_SelectIDResult">
      <Column Name="matinchi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sotinchi" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTinChi_Update" Method="sp_tblTinChi_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="matinchi" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sotinchi" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTrangThai_Delete" Method="sp_tblTrangThai_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTrangThai_Insert" Method="sp_tblTrangThai_Insert">
    <Parameter Name="matrangthai" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTrangThai_SelectAll" Method="sp_tblTrangThai_SelectAll">
    <ElementType Name="sp_tblTrangThai_SelectAllResult">
      <Column Name="matrangthai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTrangThai_SelectID" Method="sp_tblTrangThai_SelectID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblTrangThai_SelectIDResult">
      <Column Name="matrangthai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTrangThai_Update" Method="sp_tblTrangThai_Update">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="matrangthai" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tentrangthai" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTrangThai_ViewSinhVien" Method="sp_tblTrangThai_ViewSinhVien">
    <ElementType Name="sp_tblTrangThai_ViewSinhVienResult">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Mã sinh viên]" Member="Mã_sinh_viên" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Tên sinh viên]" Member="Tên_sinh_viên" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Tên lớp]" Member="Tên_lớp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Tên trạng thái]" Member="Tên_trạng_thái" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>